# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Ted's Blog
tagline:          'Ted's Blog Portal'
description:      'DevOps Engineer | Writer | Twin | #LongLiveKenMercury'
url:              blog.meralus.com
baseurl:          /

author:
  name:           'Tedley Meralus'
  url:            https://twitter.com/techgameteddy

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/tmeralus
