title: Tedley Meralus
description: My Slice of the Internet
author: Tedley Meralus
logo: /static/img/ted-circle.png
github: https://github.com/tmeralus
about: Linux Engineer

baseurl: ""
url: ""
allowsearch: false
disqus_shortname: techgameteddy
# google_analytics:
share:
  twitter_username: techgameteddy
  fb_appid: # 000000000000

# Select which social network share links to show in posts
share-links-active:
  twitter: true
  facebook: true
  linkedin: true

social-network-links:
#  email: "someone@example.com"
  facebook: tmeralus
  github: tmeralus
  twitter: tmeralus
  linkedin: tmeralus
#  youtube: tmeralus
#  reddit: yourname
#  linkedin: daattali
#  xing: yourname
#  stackoverflow: "3943160/daattali"
#  snapchat: deanat78
#  instagram: deanat78
#  spotify: yourname
#  telephone: +14159998888
#  steam: deanat78
#  twitch: yourname
#  yelp: yourname
#  telegram: yourname
#  calendly: yourname
#  mastodon: instance.url/@username
#  ORCID: your ORCID ID
#  google-scholar: your google scholar

enableTags: true
tagarray: []

paginate: 7
per_page: 7
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]

plugins:
  - jekyll-feed
