# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
#removed due to compatibility issues
#relative_permalinks: true

# Setup
title:            Ted's Blog
tagline:          'My Code and Conscience'
description:      'DevOps Engineer | Writer | Twin | #LongLiveKenMercury'
url:              blog.meralus.com
baseurl:          /

author:
  name:           'Tedley Meralus'
  url:            https://twitter.com/techgameteddy

paginate:         5
# Custom vars
version:          1.0
plugins: [jekyll-paginate]
github:
  repo:           https://github.com/tmeralus/tmeralus.github.io
